### PR TITLE
Update,Visual Improvement,Read Design,Redesign III

### PR DESCRIPTION
**Pull request by ghost**
**&: Version III.** 

Describe: Update,Visual Improvement,Read Design,Redesign III.

### CODE REVIEW

**Comment by BaseMax** [comment]
Hey,

Resolving conflicts between pglapds-pullrequest1 and master...

Regards,
Max

**Comment by BaseMax** [comment]
Hey,

It requires to was `pascal` for highlighting? @pglapds 
Please send it if need...
And please focus on the English version of the book. :+1: 
https://github.com/ET-Lang/Book

Regards,
Max

**Comment by ghost** [comment]
> 
> 
> Hey,
> 
> It requires to was `pascal` for highlighting? @pglapds
> Please send it if need...
> And please focus on the English version of the book. +1
> https://github.com/ET-Lang/Book
> 
> Regards,
> Max

Thank.

**Comment by ghost** [comment]
> 
> 
> Hey,
> 
> Resolving conflicts between pglapds-pullrequest1 and master...
> 
> Regards,
> Max

Thank ^^.

**Pull request merged**
